[package]
name = "webhook-handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.3"
serde_json = "1.0.74"
qstring = "0.7.2"
once_cell = "1.9.0"